# Generated by Django 4.0.2 on 2022-02-23 15:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('management', '0002_alter_club_members_alter_club_officers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='members',
        ),
        migrations.RemoveField(
            model_name='club',
            name='officers',
        ),
        migrations.RemoveField(
            model_name='club',
            name='sponsors',
        ),
        migrations.AlterField(
            model_name='club',
            name='participants',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
